sudo: required
services:
- docker
script:
- export REPO=bigcentech/hadoop-sbt
- export TAG_TO_USE=${TRAVIS_TAG:-snapshot}
- docker build -t $REPO:latest .
- docker tag $REPO:latest $REPO:$TAG_TO_USE
deploy:
  provider: script
  script: echo "$DOCKER_PASS" | docker login -u="$DOCKER_USER" --password-stdin &&
    docker push $REPO
  on:
    tags: true
env:
  global:
  - secure: PCZyhSKZZqnP3n09by/kzM++oFHgodsU0K3VMG4tJY/dCkc4C1TkEs0vus1Be4kJ9Jevr+ndZnIMfcFcU6oRXGTrDsR7fF9UsdOuBvl29IaI5duZZtMo0gSIMaUE7iJ6VA1pUKgjEoQo26GyIVVyPiSgJ+BDoFjy4MoUP4bOkmvMXP/z28t1H0BJjvXxXAXjjB6wRMkJor/E8TuFEZ249FraVHcXkFC89iPY9O0bRsxKx5KOOkyjRn+8QFh1SLWIGDK7OsI7ruC6f8UopAKDntDbzHKEhnH66VyFEfCvBChLOH8ecXm/C/8H/5KNg4oUG0ANq4wV/HuwvdG3ll7cYVeHydvK5m0POdRLXtZPL3jZad/mMblO2m0TD8aynpRjkz1UkfOac0mbBFOO0ywPT6sSHkq16MZcWv10SLngXQeQagDQaTZDZKyx+eaAXy+5fhIZKS4/BT8FitBnJUs3qO7mX2ZZ+LI+YZKDD836ePD2DHZegyXrHWZe+F526n73ZtQ32XN45PxTglBPCGItI1yngUfwZi3deCTJMG8I1sQE1YJwmAe/DnLJjFl9mchduSV5DDjr7QB630qaukjiXmbvh9uP2dlWd3LTzShbpHfFypvFU5cCfu+m1MMU2BCaFa/RmvcsABOHSV9R4fIgkWN/iQh0eQeRCxQkO+BJnaE=
  - secure: m+DyC2D9M7KL5VAiAaZ+0GIMSdT9Xo9gyFZ++C5EmhQ9eDBGraVG1kPzxCW7X0pFXVn7OqfFx3OLlQVqVtmQg0Cu9hGIDVbLRAZkvM7N7uWWydJpY4ou2yFuorsXA6+gpm+r7TWLPnNFw1fZ7aLHELLSL4QDIBn0nufbDF+xVnsNIgAYUTWzIkfVeq5G2isvyhRyu7lkCZ2j5kp0otJPV/piTSmLNZZ5Xr9/JftzRaJLAmApAZeNPCVj1mXHKHoeHIzwWV8Vs23bcchY0xDO7jnJmEkaRHIBGoBMWubueWwiSQMms/6osLFwNvz4iPVZzxOK7LzbS0If6OP8+eERyBbW+R0E67sThwBqxtJX5617rcPx+U8axYUSAr0FMmzBl7E1W+fUJBk5N4gDTVHeqYlhZnDRqnpoBxkHApaOAxcXNXJsLOkK/FWXLHI7QEIZ9906ya3tZHtMVcyKVLL/g+gTxJM5ldRKnhyZ5jo6he9lv8m9NSDAfly0K5xEXdWf+lYH8E2Tg8xDgvEg7Duu3kHmoZ6OT0jocASYdql1wx6hQVUMYrLaLYjy69xBoL0rR5AhuZyjxr6xjZ1PoBaP54ToiJvnBgXoYrMsBbHvg5S426OdXdZ7Wa2N/hzj818fRQ8hqZzfD+/8XjdA/MoTw/pKGRg2UQ5pJni7dhgjWRE=
