sudo: required
services:
- docker
script:
- export REPO=bigcentech/hadoop-sbt
- export TAG_TO_USE=${TRAVIS_TAG:-snapshot}
- docker build -t $REPO:latest .
- docker tag $REPO:latest $REPO:$TAG_TO_USE
deploy:
  provider: script
  script: echo "$DOCKER_PASS" | docker login -u="$DOCKER_USER" --password-stdin &&
    docker push $REPO
  on:
    tags: true
env:
  global:
  - secure: ByEC49V5LYtzYAjP6HR2vPkm48eSs0V3VTtjTiymyVBzJXDC6D7wTMJKCemvDX+MuNO+rYiUDgNLzqLArIPX8yo59WRNHOkR+74XdK0pOKm2R9BZ+T7z2YX16Q3ZVUlyfOtLZrE5aEKNlH36qtISQOPfEUc2b5INFGWRwYRAgO6rrIMkBUxnNs6Xmmk13luHLqRQhiBSSefwlozhPX+3ttzav1cBgUsWcvXzuXEmISfqvB+ti716DMIFznxjacQsDvTIl0b9dDhO9zYRktoqrZIwYGUsTHYUpaWl4sWyQZDz7dCFflAyUAQYWcIRbwoPsgJ01Vsj4Byms14OI1Pg5+mwq2A/wtJ9MmnMulmxQL82qutsgIZnVVb/hdxTFnyumJWn2Xwy3/Yeq6QljofvxYmNWRIBRbD1LbEVT3xBw1fMYiQQB9akDYHGekBhFJ2L/C/7evc3duyN2n6FRzl/nuOVDoDtw/UewNMukkGfMcKp6E81aiUKprDizvvAcuSv6QdWAzkO0XSV8S3c8px5N1YZQswbxKSmJW0Pe0PJO0hHYOEC1dWGxhCwxL6O2+WZmr/SFS9O5CKpiBpcssEWq1EKAr7qjoUpth5sLX2nC5iIBWBfn2etdMrC+3Qg6XXVLaYg2rkapOXlIAX1NV9tSlu5WcJ2Te5xGttBjZb2SCk=
  - secure: zBHnf13W+LYyTOQTKmpHAGV29VmiEdbaUoB3OZUhhrDVmTRZmolAMukHOk9ablEdb0FtS6ptBuNEgqqkPVfAQNpJuM09HflFb9Ea8N5CQmvYC732NbZpPeZ3AUtnpdfNImHQQHU+/iwq0qJJ91u46ueHsLdDUAhvEk8g+ECA8+42fbV7+ZOWbbW5dC0ZvQyNluvIUwpafgm/UpW49O7e4suodCez1Y/xWlcL1wBXkESxFhvEA4Rjyrrd95OCDbflwXlC5V92NGWMhk9cXyqW03o0VKf+mlUG8BFsZaBLuhhut1/RNuStQ+CwdW8xZtu4hv7YwrZwzE+b5MSV6e82ayOIrUN+TdzENYMTMMq6s9JTAx2kKvIWLPUc4lKW8xdG3np2rIGk9Ofg1VUjYrsQZldQT/E7Bi6J6Q8LXUbDe8T82wwlByfNZJj+QM+0bSgX5DZJAd8xZ8asDIsf1ZUdk7Cf9RpAvBn2TeX3YEXE1aCBiRDDgaLgmZ59hsub6+86eRKKCpAiHerFqcMNu1uE0z75I8uNRHL05GnI8uojnTm0hLMxNaOOPD6vpcbDku5KIAmB33Ty66Da62La9MbM8pWPgNjubKMRP8OqlI/ZSF93+43e1SXXKC0Zk5HEW3EkFmsVykMqe4FIsn5HuQ6T/OE6Y8pxmstcnR+kNPe3Ltw=
